"""add_coach_mode_to_users

Revision ID: 158da60e58be
Revises: fa92a961efb2
Create Date: 2026-02-08 20:55:04.082956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158da60e58be'
down_revision: Union[str, None] = 'fa92a961efb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coach_mode', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coach_mode')
    # ### end Alembic commands ###
