"""Add nickname report_enabled coach_mode to users

Revision ID: 2815c9ee1d81
Revises: a805b8614216
Create Date: 2026-02-07 22:43:07.581604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2815c9ee1d81'
down_revision: Union[str, None] = 'a805b8614216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('report_enabled', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('coach_mode', sa.String(length=50), server_default='angel', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coach_mode')
    op.drop_column('users', 'report_enabled')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
