"""fix_expense_table_definition

Revision ID: 5b9281fbcdf0
Revises: b82b24165090
Create Date: 2026-02-12 21:32:12.545260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b9281fbcdf0'
down_revision: Union[str, None] = 'b82b24165090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'helpfulness_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('expenses', 'helpful_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'raw_merchant',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'raw_merchant',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=True)
    op.alter_column('expenses', 'helpful_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'helpfulness_score',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
